# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: dev-ted

on:
  push:
    branches:
      - features/ted/HOL3
  workflow_dispatch:

env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/cloocus-edu-clo/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test '${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj' --no-build --verbosity normal

    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }} 

    - name: Package up project
      run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}

    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ env.LogicProjectPath }}/\*\*/\*.nupkg --skip-duplicate    

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-ted'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63710bf3fb4d417da1a7d0bb843c9415 }}
        package: .

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.TED_AZURE_CREDENTIALS }}'

    - name: Azure key vault - Get Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "dev-ted-kv"
        secrets: 'GLOBAL-PASSWORD'
      id: akv


    - name: Azure App Service Settings2
      uses: Azure/appservice-settings@v1
      with:
        app-name: 'dev-ted'
        app-settings-json: '[{ "GlobalPassword": "${{ steps.akv.outputs.GLOBAL-PASSWORD }}"}]'
      id: settings2

    - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
    - run: |
        az logout