# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: dev-ted-arm

on:
  push:
    branches:
      - features/ted/HOL3
  workflow_dispatch:

env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/cloocus-edu-clo/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.TED_AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.TED_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.TED_AZURE_RG }}
        template: ./deploy-ted.json
        parameters: ./deploy-parameter-ted.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}